/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.autocomp;

public final class R {
    public static final class attr {
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int cameraBearing=0x7f010001;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int cameraTargetLat=0x7f010002;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int cameraTargetLng=0x7f010003;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int cameraTilt=0x7f010004;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int cameraZoom=0x7f010005;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>none</code></td><td>0</td><td></td></tr>
<tr><td><code>normal</code></td><td>1</td><td></td></tr>
<tr><td><code>satellite</code></td><td>2</td><td></td></tr>
<tr><td><code>terrain</code></td><td>3</td><td></td></tr>
<tr><td><code>hybrid</code></td><td>4</td><td></td></tr>
</table>
         */
        public static final int mapType=0x7f010000;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiCompass=0x7f010006;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiRotateGestures=0x7f010007;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiScrollGestures=0x7f010008;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiTiltGestures=0x7f010009;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiZoomControls=0x7f01000a;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiZoomGestures=0x7f01000b;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int useViewLifecycle=0x7f01000c;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int zOrderOnTop=0x7f01000d;
    }
    public static final class color {
        public static final int blue=0x7f04000b;
        public static final int common_action_bar_splitter=0x7f040009;
        /**  Sign-in Button Colors 
         */
        public static final int common_signin_btn_dark_text_default=0x7f040000;
        public static final int common_signin_btn_dark_text_disabled=0x7f040002;
        public static final int common_signin_btn_dark_text_focused=0x7f040003;
        public static final int common_signin_btn_dark_text_pressed=0x7f040001;
        public static final int common_signin_btn_default_background=0x7f040008;
        public static final int common_signin_btn_light_text_default=0x7f040004;
        public static final int common_signin_btn_light_text_disabled=0x7f040006;
        public static final int common_signin_btn_light_text_focused=0x7f040007;
        public static final int common_signin_btn_light_text_pressed=0x7f040005;
        public static final int common_signin_btn_text_dark=0x7f04000e;
        public static final int common_signin_btn_text_light=0x7f04000f;
        public static final int cream=0x7f04000a;
        public static final int green=0x7f04000c;
        public static final int white=0x7f04000d;
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 

         Customize dimensions originally defined in res/values/dimens.xml (such as
         screen margins) for sw720dp devices (e.g. 10" tablets) in landscape here.
    
         */
        public static final int activity_horizontal_margin=0x7f070000;
        public static final int activity_vertical_margin=0x7f070001;
    }
    public static final class drawable {
        public static final int abs__ic_clear_search_api_holo_light=0x7f020000;
        public static final int auto=0x7f020001;
        public static final int back=0x7f020002;
        public static final int btn_ic_red_cross_normal=0x7f020003;
        public static final int btn_ic_red_cross_pressed=0x7f020004;
        public static final int bus=0x7f020005;
        public static final int call=0x7f020006;
        public static final int center=0x7f020007;
        public static final int clock2=0x7f020008;
        public static final int common_signin_btn_icon_dark=0x7f020009;
        public static final int common_signin_btn_icon_disabled_dark=0x7f02000a;
        public static final int common_signin_btn_icon_disabled_focus_dark=0x7f02000b;
        public static final int common_signin_btn_icon_disabled_focus_light=0x7f02000c;
        public static final int common_signin_btn_icon_disabled_light=0x7f02000d;
        public static final int common_signin_btn_icon_focus_dark=0x7f02000e;
        public static final int common_signin_btn_icon_focus_light=0x7f02000f;
        public static final int common_signin_btn_icon_light=0x7f020010;
        public static final int common_signin_btn_icon_normal_dark=0x7f020011;
        public static final int common_signin_btn_icon_normal_light=0x7f020012;
        public static final int common_signin_btn_icon_pressed_dark=0x7f020013;
        public static final int common_signin_btn_icon_pressed_light=0x7f020014;
        public static final int common_signin_btn_text_dark=0x7f020015;
        public static final int common_signin_btn_text_disabled_dark=0x7f020016;
        public static final int common_signin_btn_text_disabled_focus_dark=0x7f020017;
        public static final int common_signin_btn_text_disabled_focus_light=0x7f020018;
        public static final int common_signin_btn_text_disabled_light=0x7f020019;
        public static final int common_signin_btn_text_focus_dark=0x7f02001a;
        public static final int common_signin_btn_text_focus_light=0x7f02001b;
        public static final int common_signin_btn_text_light=0x7f02001c;
        public static final int common_signin_btn_text_normal_dark=0x7f02001d;
        public static final int common_signin_btn_text_normal_light=0x7f02001e;
        public static final int common_signin_btn_text_pressed_dark=0x7f02001f;
        public static final int common_signin_btn_text_pressed_light=0x7f020020;
        public static final int dlr=0x7f020021;
        public static final int gflag=0x7f020022;
        public static final int gradient_bg=0x7f020023;
        public static final int gradient_bg_hover=0x7f020024;
        public static final int ic_action_refresh=0x7f020025;
        public static final int ic_launcher=0x7f020026;
        public static final int ic_plusone_medium_off_client=0x7f020027;
        public static final int ic_plusone_small_off_client=0x7f020028;
        public static final int ic_plusone_standard_off_client=0x7f020029;
        public static final int ic_plusone_tall_off_client=0x7f02002a;
        public static final int image_bg=0x7f02002b;
        public static final int list_selector_early=0x7f02002c;
        public static final int listview_selector=0x7f02002d;
        public static final int logo_actionbar2=0x7f02002e;
        public static final int mapcolor_icon=0x7f02002f;
        public static final int marker_end=0x7f020030;
        public static final int marker_nyc_bus=0x7f020031;
        public static final int marker_nyc_subway=0x7f020032;
        public static final int marker_start=0x7f020033;
        public static final int phone24=0x7f020034;
        public static final int phone32=0x7f020035;
        public static final int place=0x7f020036;
        public static final int rupee=0x7f020037;
        public static final int search_route=0x7f020038;
        public static final int search_station=0x7f020039;
        public static final int searchitx=0x7f02003a;
        public static final int step_generic_bus=0x7f02003b;
        public static final int step_generic_rail=0x7f02003c;
        public static final int step_ghetto=0x7f02003d;
        public static final int step_nyc_bus=0x7f02003e;
        public static final int step_wait=0x7f02003f;
        public static final int step_walk_man=0x7f020040;
        public static final int taxi=0x7f020041;
        public static final int textshadow=0x7f020042;
        public static final int textview_shadow=0x7f020043;
        public static final int train=0x7f020044;
        public static final int walking=0x7f020045;
    }
    public static final class id {
        public static final int Go=0x7f05001d;
        public static final int VerticalLine=0x7f050012;
        public static final int ab_text=0x7f050005;
        public static final int action_settings=0x7f05003d;
        public static final int artist=0x7f050034;
        public static final int autoCs=0x7f050022;
        public static final int autocompleteBus=0x7f05002e;
        public static final int autocompleteBusBar=0x7f050006;
        public static final int autocompleteFrom=0x7f050017;
        public static final int autocompleteTo=0x7f05001a;
        public static final int base=0x7f050039;
        public static final int btnBus=0x7f050014;
        public static final int btnTrain=0x7f050013;
        public static final int btncall=0x7f050027;
        public static final int btncallCabs=0x7f05002a;
        public static final int btndestination=0x7f050011;
        public static final int busStops=0x7f05000a;
        public static final int changer=0x7f05002f;
        public static final int deldest=0x7f05001b;
        public static final int delsrc=0x7f050018;
        public static final int dialogButtonOK=0x7f050040;
        public static final int duration=0x7f050036;
        public static final int editTexts=0x7f05001c;
        public static final int fareFinal=0x7f050037;
        public static final int fromtoTime=0x7f050035;
        public static final int hybrid=0x7f050004;
        public static final int image=0x7f050041;
        public static final int imageDur=0x7f05002d;
        public static final int imageView1=0x7f050023;
        public static final int info=0x7f050028;
        public static final int info1=0x7f05003a;
        public static final int info2=0x7f05003b;
        public static final int info3=0x7f05003c;
        public static final int item_text=0x7f050043;
        public static final int lblListHeader=0x7f050031;
        public static final int lblListItem=0x7f050032;
        public static final int legsLen=0x7f05000b;
        public static final int list=0x7f05002c;
        public static final int listStops=0x7f050009;
        public static final int listView=0x7f050015;
        public static final int list_image=0x7f050030;
        public static final int llContainer=0x7f050038;
        public static final int lvExp=0x7f05000d;
        public static final int map=0x7f05000f;
        public static final int mapper=0x7f050042;
        public static final int mapsStop=0x7f050008;
        public static final int mrkend=0x7f050019;
        public static final int mrkstart=0x7f050016;
        public static final int msgView=0x7f05001e;
        public static final int none=0x7f050000;
        public static final int normal=0x7f050001;
        public static final int pager=0x7f05000e;
        public static final int regButton=0x7f05001f;
        public static final int satellite=0x7f050002;
        public static final int srchImg=0x7f050007;
        public static final int stops=0x7f05003f;
        public static final int terrain=0x7f050003;
        public static final int textAuto=0x7f050021;
        public static final int textCabs=0x7f050029;
        public static final int textCs=0x7f05002b;
        public static final int textRup=0x7f050025;
        public static final int textTaxName=0x7f050024;
        public static final int textV=0x7f050026;
        public static final int textV1=0x7f05003e;
        public static final int textView1=0x7f050020;
        public static final int title=0x7f050033;
        public static final int transits=0x7f05000c;
        public static final int weather=0x7f050010;
    }
    public static final class layout {
        public static final int action_text=0x7f030000;
        public static final int actionbar=0x7f030001;
        public static final int activity_activity_transit=0x7f030002;
        public static final int activity_activity_weather=0x7f030003;
        public static final int activity_bus_=0x7f030004;
        public static final int activity_bus_mark=0x7f030005;
        public static final int activity_bus_stops=0x7f030006;
        public static final int activity_detailed_summary=0x7f030007;
        public static final int activity_display=0x7f030008;
        public static final int activity_first=0x7f030009;
        public static final int activity_main=0x7f03000a;
        public static final int activity_map=0x7f03000b;
        public static final int activity_map_radius=0x7f03000c;
        public static final int activity_mapping=0x7f03000d;
        public static final int activity_marker_test=0x7f03000e;
        public static final int activity_places_autocomplete=0x7f03000f;
        public static final int activity_radius=0x7f030010;
        public static final int activity_register=0x7f030011;
        public static final int activity_stops=0x7f030012;
        public static final int adapter_list_row=0x7f030013;
        public static final int autoview=0x7f030014;
        public static final int aview=0x7f030015;
        public static final int back=0x7f030016;
        public static final int busmark=0x7f030017;
        public static final int cabview=0x7f030018;
        public static final int custom_button=0x7f030019;
        public static final int customized_list_view=0x7f03001a;
        public static final int cview=0x7f03001b;
        public static final int displaymap=0x7f03001c;
        public static final int extra_layout=0x7f03001d;
        public static final int fragment_transit=0x7f03001e;
        public static final int list_group=0x7f03001f;
        public static final int list_item=0x7f030020;
        public static final int list_items=0x7f030021;
        public static final int list_row=0x7f030022;
        public static final int lview=0x7f030023;
        public static final int main=0x7f030024;
        public static final int marker=0x7f030025;
        public static final int none_tview=0x7f030026;
        public static final int radius=0x7f030027;
        public static final int rowview=0x7f030028;
        public static final int rowviewbus=0x7f030029;
        public static final int stops_dialog=0x7f03002a;
        public static final int textshadow=0x7f03002b;
        public static final int textview_shadow=0x7f03002c;
        public static final int tview=0x7f03002d;
    }
    public static final class menu {
        public static final int activity_transit=0x7f090000;
        public static final int activity_weather=0x7f090001;
        public static final int bus_=0x7f090002;
        public static final int bus_mark=0x7f090003;
        public static final int bus_stops=0x7f090004;
        public static final int detailed_summary=0x7f090005;
        public static final int display=0x7f090006;
        public static final int main=0x7f090007;
        public static final int mainmenu=0x7f090008;
        public static final int map=0x7f090009;
        public static final int map_radius=0x7f09000a;
        public static final int mapping=0x7f09000b;
        public static final int marker_test=0x7f09000c;
        public static final int places_autocomplete=0x7f09000d;
        public static final int radius=0x7f09000e;
        public static final int stops=0x7f09000f;
    }
    public static final class string {
        public static final int ArrT=0x7f06001e;
        public static final int Dist=0x7f060022;
        public static final int Dur=0x7f060023;
        public static final int FROM=0x7f06001c;
        public static final int Fare=0x7f060024;
        public static final int Now=0x7f06001f;
        public static final int Rs=0x7f060025;
        public static final int Select=0x7f060029;
        public static final int TO=0x7f06001d;
        public static final int action_settings=0x7f06001a;
        public static final int app_name=0x7f060019;
        /**   Title for notification shown when GooglePlayServices needs to be
        enabled for a application to work. [CHAR LIMIT=70] 
         */
        public static final int auth_client_needs_enabling_title=0x7f060014;
        /**   Title for notification shown when GooglePlayServices needs to be
        installed for a application to work. [CHAR LIMIT=70] 
         */
        public static final int auth_client_needs_installation_title=0x7f060015;
        /**   Title for notification shown when GooglePlayServices needs to be
        udpated for a application to work. [CHAR LIMIT=70] 
         */
        public static final int auth_client_needs_update_title=0x7f060016;
        /**   Title for notification shown when GooglePlayServices is unavailable [CHAR LIMIT=42] 
         */
        public static final int auth_client_play_services_err_notification_msg=0x7f060017;
        /**   Requested by string saying which app requested the notification. [CHAR LIMIT=42] 
         */
        public static final int auth_client_requested_by_msg=0x7f060018;
        /**   Title for notification shown when a bad version of GooglePlayServices
        has been installed and needs correction for an application to work.
        [CHAR LIMIT=70] 
         */
        public static final int auth_client_using_bad_version_title=0x7f060013;
        public static final int clock=0x7f06002c;
        /**  Button in confirmation dialog to enable Google Play services.  Clicking it
        will direct user to application settings of Google Play services where they
        can enable it [CHAR LIMIT=40] 
         */
        public static final int common_google_play_services_enable_button=0x7f060006;
        /**  Message in confirmation dialog informing user they need to enable
        Google Play services in application settings [CHAR LIMIT=NONE] 
         */
        public static final int common_google_play_services_enable_text=0x7f060005;
        /**  Title of confirmation dialog informing user they need to enable
        Google Play services in application settings [CHAR LIMIT=40] 
         */
        public static final int common_google_play_services_enable_title=0x7f060004;
        /**  Button in confirmation dialog for installing Google Play services [CHAR LIMIT=40] 
         */
        public static final int common_google_play_services_install_button=0x7f060003;
        /**  (For phones) Message in confirmation dialog informing user that
        they need to install Google Play services (from Play Store) [CHAR LIMIT=NONE] 
         */
        public static final int common_google_play_services_install_text_phone=0x7f060001;
        /**  (For tablets) Message in confirmation dialog informing user that
        they need to install Google Play services (from Play Store) [CHAR LIMIT=NONE] 
         */
        public static final int common_google_play_services_install_text_tablet=0x7f060002;
        /**  Title of confirmation dialog informing user that they need to install
        Google Play services (from Play Store) [CHAR LIMIT=40] 
         */
        public static final int common_google_play_services_install_title=0x7f060000;
        /**  Message in confirmation dialog informing the user that they provided an invalid account. [CHAR LIMIT=NONE] 
         */
        public static final int common_google_play_services_invalid_account_text=0x7f06000c;
        /**  Title of confirmation dialog informing the user that they provided an invalid account. [CHAR LIMIT=40] 
         */
        public static final int common_google_play_services_invalid_account_title=0x7f06000b;
        /**  Message in confirmation dialog informing the user that a network error occurred. [CHAR LIMIT=NONE] 
         */
        public static final int common_google_play_services_network_error_text=0x7f06000a;
        /**  Title of confirmation dialog informing the user that a network error occurred. [CHAR LIMIT=40] 
         */
        public static final int common_google_play_services_network_error_title=0x7f060009;
        /**  Message in confirmation dialog informing user there is an unknown issue in Google Play
        services [CHAR LIMIT=NONE] 
         */
        public static final int common_google_play_services_unknown_issue=0x7f06000d;
        /**  Message in confirmation dialog informing user that Google Play services is not supported on their device [CHAR LIMIT=NONE] 
         */
        public static final int common_google_play_services_unsupported_text=0x7f06000f;
        /**  Title of confirmation dialog informing user that Google Play services is not supported on their device [CHAR LIMIT=40] 
         */
        public static final int common_google_play_services_unsupported_title=0x7f06000e;
        /**  Button in confirmation dialog for updating Google Play services [CHAR LIMIT=40] 
         */
        public static final int common_google_play_services_update_button=0x7f060010;
        /**  Message in confirmation dialog informing user that they need to update
        Google Play services (from Play Store) [CHAR LIMIT=NONE] 
         */
        public static final int common_google_play_services_update_text=0x7f060008;
        /**  Title of confirmation dialog informing user that they need to update
        Google Play services (from Play Store) [CHAR LIMIT=40] 
         */
        public static final int common_google_play_services_update_title=0x7f060007;
        /**  Sign-in button text [CHAR LIMIT=15] 
         */
        public static final int common_signin_button_text=0x7f060011;
        /**  Long form sign-in button text [CHAR LIMIT=30] 
         */
        public static final int common_signin_button_text_long=0x7f060012;
        public static final int degree=0x7f06002b;
        public static final int dummy=0x7f06002f;
        public static final int error_when_retrieving_data=0x7f060020;
        public static final int hello_world=0x7f06001b;
        public static final int rupees=0x7f06002a;
        public static final int title_activity_activity_transit=0x7f060028;
        public static final int title_activity_activity_weather=0x7f060030;
        public static final int title_activity_main=0x7f06002d;
        public static final int title_activity_map=0x7f060021;
        public static final int title_activity_map_radius=0x7f060027;
        public static final int title_activity_mapping=0x7f060026;
        public static final int user_id_text=0x7f06002e;
    }
    public static final class style {
        /** 
        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f080002;
        public static final int MyActionBar=0x7f080001;
        public static final int MyTheme=0x7f080000;
    }
    public static final class styleable {
        /** Attributes that can be used with a MapAttrs.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #MapAttrs_cameraBearing com.example.autocomp:cameraBearing}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_cameraTargetLat com.example.autocomp:cameraTargetLat}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_cameraTargetLng com.example.autocomp:cameraTargetLng}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_cameraTilt com.example.autocomp:cameraTilt}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_cameraZoom com.example.autocomp:cameraZoom}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_mapType com.example.autocomp:mapType}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_uiCompass com.example.autocomp:uiCompass}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_uiRotateGestures com.example.autocomp:uiRotateGestures}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_uiScrollGestures com.example.autocomp:uiScrollGestures}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_uiTiltGestures com.example.autocomp:uiTiltGestures}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_uiZoomControls com.example.autocomp:uiZoomControls}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_uiZoomGestures com.example.autocomp:uiZoomGestures}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_useViewLifecycle com.example.autocomp:useViewLifecycle}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_zOrderOnTop com.example.autocomp:zOrderOnTop}</code></td><td></td></tr>
           </table>
           @see #MapAttrs_cameraBearing
           @see #MapAttrs_cameraTargetLat
           @see #MapAttrs_cameraTargetLng
           @see #MapAttrs_cameraTilt
           @see #MapAttrs_cameraZoom
           @see #MapAttrs_mapType
           @see #MapAttrs_uiCompass
           @see #MapAttrs_uiRotateGestures
           @see #MapAttrs_uiScrollGestures
           @see #MapAttrs_uiTiltGestures
           @see #MapAttrs_uiZoomControls
           @see #MapAttrs_uiZoomGestures
           @see #MapAttrs_useViewLifecycle
           @see #MapAttrs_zOrderOnTop
         */
        public static final int[] MapAttrs = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003,
            0x7f010004, 0x7f010005, 0x7f010006, 0x7f010007,
            0x7f010008, 0x7f010009, 0x7f01000a, 0x7f01000b,
            0x7f01000c, 0x7f01000d
        };
        /**
          <p>This symbol is the offset where the {@link com.example.autocomp.R.attr#cameraBearing}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.example.autocomp:cameraBearing
        */
        public static final int MapAttrs_cameraBearing = 1;
        /**
          <p>This symbol is the offset where the {@link com.example.autocomp.R.attr#cameraTargetLat}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.example.autocomp:cameraTargetLat
        */
        public static final int MapAttrs_cameraTargetLat = 2;
        /**
          <p>This symbol is the offset where the {@link com.example.autocomp.R.attr#cameraTargetLng}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.example.autocomp:cameraTargetLng
        */
        public static final int MapAttrs_cameraTargetLng = 3;
        /**
          <p>This symbol is the offset where the {@link com.example.autocomp.R.attr#cameraTilt}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.example.autocomp:cameraTilt
        */
        public static final int MapAttrs_cameraTilt = 4;
        /**
          <p>This symbol is the offset where the {@link com.example.autocomp.R.attr#cameraZoom}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.example.autocomp:cameraZoom
        */
        public static final int MapAttrs_cameraZoom = 5;
        /**
          <p>This symbol is the offset where the {@link com.example.autocomp.R.attr#mapType}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>none</code></td><td>0</td><td></td></tr>
<tr><td><code>normal</code></td><td>1</td><td></td></tr>
<tr><td><code>satellite</code></td><td>2</td><td></td></tr>
<tr><td><code>terrain</code></td><td>3</td><td></td></tr>
<tr><td><code>hybrid</code></td><td>4</td><td></td></tr>
</table>
          @attr name com.example.autocomp:mapType
        */
        public static final int MapAttrs_mapType = 0;
        /**
          <p>This symbol is the offset where the {@link com.example.autocomp.R.attr#uiCompass}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.example.autocomp:uiCompass
        */
        public static final int MapAttrs_uiCompass = 6;
        /**
          <p>This symbol is the offset where the {@link com.example.autocomp.R.attr#uiRotateGestures}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.example.autocomp:uiRotateGestures
        */
        public static final int MapAttrs_uiRotateGestures = 7;
        /**
          <p>This symbol is the offset where the {@link com.example.autocomp.R.attr#uiScrollGestures}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.example.autocomp:uiScrollGestures
        */
        public static final int MapAttrs_uiScrollGestures = 8;
        /**
          <p>This symbol is the offset where the {@link com.example.autocomp.R.attr#uiTiltGestures}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.example.autocomp:uiTiltGestures
        */
        public static final int MapAttrs_uiTiltGestures = 9;
        /**
          <p>This symbol is the offset where the {@link com.example.autocomp.R.attr#uiZoomControls}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.example.autocomp:uiZoomControls
        */
        public static final int MapAttrs_uiZoomControls = 10;
        /**
          <p>This symbol is the offset where the {@link com.example.autocomp.R.attr#uiZoomGestures}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.example.autocomp:uiZoomGestures
        */
        public static final int MapAttrs_uiZoomGestures = 11;
        /**
          <p>This symbol is the offset where the {@link com.example.autocomp.R.attr#useViewLifecycle}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.example.autocomp:useViewLifecycle
        */
        public static final int MapAttrs_useViewLifecycle = 12;
        /**
          <p>This symbol is the offset where the {@link com.example.autocomp.R.attr#zOrderOnTop}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.example.autocomp:zOrderOnTop
        */
        public static final int MapAttrs_zOrderOnTop = 13;
    };
}
